name: test
on:
  workflow_dispatch:
  pull_request:
    paths:
    - src/**
    - pyproject.toml
    - tests/**
    - "*_requirements.txt"
    - tox.ini
    - .github/workflows/test.yml
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python:
        - 3.8
        - 3.9
        - '3.10'
        - 3.11
        - 3.12
        - 3.13
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: test
      run: make test
